export const PRESCRIPT = {
  'apt.globals.set("key", "value");': '设置一个全局变量',
  'apt.globals.get("key");': '获取一个全局变量',
  'apt.globals.delete("key");': '删除一个全局变量',
  'apt.globals.clear();': '清空全局变量',
  'apt.variables.set("key", "value");': '设置一个环境变量',
  'apt.variables.get("key");': '获取一个环境变量',
  'apt.variables.delete("key");': '删除一个环境变量',
  'apt.variables.getPreUrl();': '获取当前环境前置url',
  'apt.variables.getName();': '获取当前环境名称',
  'apt.variables.getCollection();': '获取当前环境变量集合',
  'apt.variables.clear();': '清空环境变量',
  'apt.setRequestQuery("key", "value");': '设置一个请求query',
  'apt.removeRequestQuery("key");': '删除一个请求query',
  'apt.setRequestHeader("key", "value");': '添加一个请求头',
  'apt.removeRequestHeader("key");': '删除一个请求头',
  'apt.setRequestBody("key", "value");': '添加一个请求body',
  'apt.removeRequestBody("key");': '删除一个请求body',
  '$.ajax({\n\t"url":"https://echo.apipost.cn/token.php",\n\t"method":"POST",\n\t"async":false,\n\t"content-type":"appicateion/json",\n\t"data":JSON.stringify({\n\t\t"email":"admin@admin.com", \n\t\t"password":"密码"\n\t}),\n\t"success":function(response){\n\t\tresponse = typeof response == "object" ? response : JSON.parse(response);\n\t\tconsole.log(response);\n\t\tapt.variables.set("token", response.token);\n\t}\n});':
    '发送一个请求',
}; // 预执行脚本
export const TEST = {
  'apt.assert(\'response.raw.responseText=="test"\');': '测试响应内容是否为test',
  "apt.assert('response.raw.status==200');": '测试响应码是否为200',
  'apt.assert(\'response.raw.type=="json"\');': '测试响应内容格式是否为json',
  "apt.assert('response.raw.responseTime>=100');": '测试响应时间是否大于100ms',
  "apt.assert('response.json.errcode==1');": '测试响应Json对象的errcode属性是否为1',
  "apt.assert('response.json.errcode!=1');": '测试响应Json对象的errcode是否不为1',
  "apt.assert('response.json.errcode>=1');": '测试响应Json对象的errcode是否大于等于1',
  "apt.assert('response.json.errcode==null');": '测试响应Json对象的errcode是否为null',
  "apt.assert('response.json.errcode!=null');": '测试响应Json对象的errcode是否不为null',
  'apt.assert(\'response.headers["server"] == "nginx"\');': '测试响应头server是否为nginx',
  'apt.assert(\'response.headers["content-encoding"] == "gzip"\');':
    '测试响应头content-encoding是否为gzip',
  'apt.globals.set("key", "value");': '设置一个全局变量',
  'apt.globals.get("key");': '获取一个全局变量',
  'apt.globals.delete("key");': '删除一个全局变量',
  'apt.globals.clear();': '清空全局变量',
  'apt.variables.set("key", "value");': '设置一个环境变量',
  'apt.variables.get("key");': '获取一个环境变量',
  'apt.variables.delete("key");': '删除一个环境变量',
  'apt.variables.getPreUrl();': '获取当前环境前置url',
  'apt.variables.getName();': '获取当前环境名称',
  'apt.variables.getCollection();': '获取当前环境变量集合',
  'apt.variables.clear();': '清空环境变量',
  '$.ajax({\n\t"url":"https://echo.apipost.cn/token.php",\n\t"method":"POST",\n\t"async":false,\n\t"content-type":"appicateion/json",\n\t"data":JSON.stringify({\n\t\t"email":"admin@admin.com", \n\t\t"password":"密码"\n\t}),\n\t"success":function(response){\n\t\tresponse = typeof response == "object" ? response : JSON.parse(response);\n\t\tconsole.log(response);\n\t\tapt.variables.set("token", response.token);\n\t}\n});':
    '发送一个请求',
  // 'apt.sendRequest("http://echo.apipost.cn/get.php", function (response) {\n\tapt.variables.set("var", response.headers["User-Agent"]);\n});': "发送一个请求"
}; // 测试用例
