const createDependencyProposals = (range) => [
  {
    label: 'console.log',
    kind: monaco.languages.CompletionItemKind.Function,
    documentation: '打印一条日志到控制台',
    insertText: 'console.log()',
    range,
  },
  {
    label: 'console.warn',
    kind: monaco.languages.CompletionItemKind.Function,
    documentation: '打印一条警告到控制台',
    insertText: 'console.log()',
    range,
  },
  {
    label: 'console.info',
    kind: monaco.languages.CompletionItemKind.Function,
    documentation: '打印一条信息到控制台',
    insertText: 'console.error()',
    range,
  },
  {
    label: 'console.error',
    kind: monaco.languages.CompletionItemKind.Function,
    documentation: '打印一条错误到控制台',
    insertText: 'console.error()',
    range,
  },
  {
    label: 'request',
    kind: monaco.languages.CompletionItemKind.Function,
    documentation: '当前请求参数对象',
    insertText: 'request',
    range,
  },
  {
    label: 'request.url',
    kind: monaco.languages.CompletionItemKind.Function,
    documentation: '当前请求URL',
    insertText: 'request.url',
    range,
  },
  {
    label: 'request.method',
    kind: monaco.languages.CompletionItemKind.Function,
    documentation: '当前请求Method',
    insertText: 'request.method',
    range,
  },
  {
    label: 'request.timeout',
    kind: monaco.languages.CompletionItemKind.Function,
    documentation: '当前请求超时时间',
    insertText: 'request.timeout',
    range,
  },
  {
    label: 'request.contentType',
    kind: monaco.languages.CompletionItemKind.Function,
    documentation: '当前请求contentType',
    insertText: 'request.contentType',
    range,
  },
  {
    label: 'request.request_bodys',
    kind: monaco.languages.CompletionItemKind.Function,
    documentation: '当前请求的请求体',
    insertText: 'request.request_bodys',
    range,
  },
  {
    label: 'request.request_headers',
    kind: monaco.languages.CompletionItemKind.Function,
    documentation: '当前请求的请求头',
    insertText: 'request.request_headers',
    range,
  },
  {
    label: 'request.request_querys',
    kind: monaco.languages.CompletionItemKind.Function,
    documentation: '当前请求的query',
    insertText: 'request.request_querys',
    range,
  },
  {
    label: 'response',
    kind: monaco.languages.CompletionItemKind.Function,
    documentation: '当前请求响应对象',
    insertText: 'response',
    range,
  },
  {
    label: 'response.json',
    kind: monaco.languages.CompletionItemKind.Function,
    documentation: 'json格式的响应数据(如果是)',
    insertText: 'response.json',
    range,
  },
  {
    label: 'response.headers',
    kind: monaco.languages.CompletionItemKind.Function,
    documentation: '当前请求响应头',
    insertText: 'response.headers',
    range,
  },
  {
    label: 'response.cookies',
    kind: monaco.languages.CompletionItemKind.Function,
    documentation: '当前请求响应cookie',
    insertText: 'response.cookies',
    range,
  },
  {
    label: 'response.raw',
    kind: monaco.languages.CompletionItemKind.Function,
    documentation: '原始响应数据',
    insertText: 'response.raw',
    range,
  },
  {
    label: 'response.raw.status',
    kind: monaco.languages.CompletionItemKind.Function,
    documentation: '响应状态码(200、301、404等)',
    insertText: 'response.raw.status',
    range,
  },
  {
    label: 'response.raw.responseTime',
    kind: monaco.languages.CompletionItemKind.Function,
    documentation: '响应时间(毫秒)',
    insertText: 'response.raw.responseTime',
    range,
  },
  {
    label: 'response.raw.type',
    kind: monaco.languages.CompletionItemKind.Function,
    documentation: '响应类型(json等)',
    insertText: 'response.raw.type',
    range,
  },
  {
    label: 'response.raw.responseText',
    kind: monaco.languages.CompletionItemKind.Function,
    documentation: '响应文本',
    insertText: 'response.raw.responseText',
    range,
  },
];

export default createDependencyProposals;
